const fs=require('fs'),path=require('path'),crypto=require('crypto'),https=require('https'),cheerio=require('cheerio');const prettier=require('prettier');
const root=path.resolve('copia-dronex');const origin='https://eurodronex.com';const manifest={};const downloads=new Map();const digest=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,12);const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s)};
const get=url=>new Promise((ok,no)=>https.get(url,r=>{if(r.statusCode>=300&&r.statusCode<400)return ok(get(new URL(r.headers.location,url).href));let a=[];r.on('data',d=>a.push(d));r.on('end',()=>r.statusCode===200?ok(Buffer.concat(a)):no(Error(url+' '+r.statusCode)))}).on('error',no));
function asset(raw){if(!raw||raw.startsWith('data:')||raw.startsWith('#'))return raw;let url;try{url=new URL(raw,origin).href}catch{return raw}if(!/\.(?:png|jpe?g|webp|svg|gif|avif|woff2?|ttf|otf|mp4)(?:[?#]|$)/i.test(url))return raw;const ext=new URL(url).pathname.split('.').pop().toLowerCase();const name='assets/'+(/woff|ttf|otf/.test(ext)?'fonts/':'img/')+digest(url)+'.'+ext;downloads.set(url,name);manifest[url]='/'+name;return '/'+name;}
function localUrls(css){return css.replace(/url\((['"]?)([^)'"\s]+)\1\)/g,(all,q,url)=>'url("'+asset(url)+'")').replace(/--lzl-bg-img:[^;}]+[;]?/g,'');}
function clean($,node){const dom=$(node);dom.find('script,noscript,style,iframe,.elementor-sticky__spacer,.elementor-message').remove();dom.find('*').addBack().each((i,e)=>{const el=$(e);if(e.type!=='tag')return;for(const k of Object.keys(e.attribs||{})){if(k.startsWith('on')||k.startsWith('data-lzl')||['data-settings','data-element_type','data-e-type','data-widget_type','data-focus-index','data-tab-index'].includes(k))el.removeAttr(k);}
 el.removeClass('lzl elementor-invisible animated fadeIn fadeInUp elementor-sticky--active elementor-sticky--effects elementor-section--handles-inside').addClass(el.hasClass('e-con')?'e-lazyloaded':'');
 if(el.hasClass('elementor-sticky'))el.removeAttr('style');if(el.hasClass('e-n-menu-wrapper'))el.removeAttr('style');
 if(e.name==='img'){const original=$(e).attr('src');el.attr('src',asset(original));el.removeAttr('srcset sizes data-srcset');if(!el.attr('alt'))el.attr('alt','EurodroneX');}
 for(const attr of ['href','data-column-clickable']){const v=el.attr(attr);if(v&&/^https?:\/\/(www\.)?eurodronex\.com/.test(v)){const u=new URL(v);el.attr(attr,u.pathname+u.search+u.hash)}}
 if(el.attr('style'))el.attr('style',localUrls(el.attr('style')));
 if(e.name==='summary')el.removeAttr('tabindex aria-controls');
 });return dom;}
async function html(s){return await prettier.format(s,{parser:'html',useTabs:true,tabWidth:4,printWidth:120,htmlWhitespaceSensitivity:'ignore'}).catch(()=>s)}
function phpstr(v){return "'"+String(v||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")+"'"}
(async()=>{
const pages=JSON.parse(fs.readFileSync(path.join(root,'docs/pages.json')));let headerWritten=false;const catalog=[];
for(const page of pages){const $=cheerio.load(fs.readFileSync(path.join(root,'docs/source',page.slug+'.html'),'utf8'));
// Resolve lazy image URLs before removing the optimizer attributes.
$('img').each((i,e)=>{const el=$(e);for(const a of ['data-lzl-src','data-src'])if(el.attr(a))el.attr('src',el.attr(a));});
const cssFiles=[];$('style').each((i,e)=>{const id=$(e).attr('id')||'inline';if(/cmplz|qlwapp|hostinger/.test(id))return;let css=localUrls($(e).text());if(!css.trim()||/body\{opacity:0/.test(css))return;const file='assets/css/'+id.replace(/[^a-z0-9-]/gi,'')+'-'+digest(css)+'.css';write(file,css);cssFiles.push('/'+file)});
const bodyClass=$('body').attr('class').replace(/cmplz-\S+/g,'').trim();let main=$('body > div.elementor').first();if(!main.length)main=$('main').first();if(!main.length)throw Error('No content '+page.slug);
const mainClass=main.attr('class')||'',mainId=main.attr('data-elementor-id')||'';const title=$('title').text(),description=$('meta[name=description]').attr('content')||title;
const schema=$('script[type="application/ld+json"]').first().text();if(schema)write('services/data/'+page.slug+'-schema.json',schema);
if(!headerWritten){write('components/header.php',await html($.html(clean($,$('header').first()))));write('components/footer.php',await html($.html(clean($,$('footer').first()))));headerWritten=true;}
const includes=[];const sourceBlocks=main.children().toArray();let n=0;
for(const block of sourceBlocks){if(['script','style'].includes(block.name))continue;const el=clean($,block);if(el.hasClass('elementor-hidden-desktop')&&el.hasClass('elementor-hidden-tablet')&&el.hasClass('elementor-hidden-mobile'))continue;
 const heading=el.find('h1,h2,h3').first().text().trim();const label=heading.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55)||'contenido';let file=page.slug+'-'+String(++n).padStart(2,'0')+'-'+label+'.php';
 el.find('form').each((i,f)=>{const form=$(f);form.attr({method:'post',action:'/services/contact_process.php',enctype:'multipart/form-data','data-contact-form':''});form.find('input[type=hidden],.elementor-field-type-recaptcha_v3,.elementor-field-type-recaptcha').remove();const mapping={name:'nombre',email:'email',message:'mensaje',field_1cfe439:'empresa',field_fa09154:'telefono',field_1fe42de:'tipoCliente',field_34995c2:'tipoServicio',field_2011b8b:'tipoEdificio',field_3c3af2e:'ubicacion',field_5e1f553:'urgencia'};form.find('input,select,textarea').each((j,input)=>{const item=$(input),old=item.attr('name')||'';const key=old.match(/^form_fields\[([^\]]+)\]/)?.[1];if(item.attr('type')==='file'){item.attr({name:'imagenes[]',accept:'image/jpeg,image/png,image/webp',multiple:''});}else if(key&&mapping[key])item.attr('name',mapping[key]);});form.prepend('<input type="hidden" name="csrf" value="EDX_CSRF_TOKEN"><input type="text" name="website" class="form-trap" tabindex="-1" autocomplete="off" aria-hidden="true"><p class="form-status" role="status" hidden></p>');form.find('[name=nombre]').attr('required','');});
 let text=await html($.html(el));text=text.replaceAll('EDX_CSRF_TOKEN',"<?= e(csrf_token()) ?>");write('components/'+file,text);includes.push(file);
}
const canonical=new URL(page.url).pathname;const css=JSON.stringify(cssFiles);write('services/data/'+page.slug+'-styles.json',css);
write(page.slug+'.php',`<?php\n\t$pageTitle = ${phpstr(title)};\n\t$pageDescription = ${phpstr(description)};\n\t$pageCanonical = ${phpstr(canonical)};\n\t$pageKey = ${phpstr(page.slug)};\n\tinclude_once 'services/bootstrap.php';\n?>\n<!doctype html>\n<html lang="es">\n\t<head>\n\t\t<?php include_once 'services/common-head.php'; ?>\n\t</head>\n\t<body class="${bodyClass}">\n\t\t<?php include_once 'components/header.php'; ?>\n\t\t<main id="contenido" class="${mainClass}" data-elementor-id="${mainId}">\n${includes.map(f=>"\t\t\t<?php include 'components/"+f+"'; ?>").join('\n')}\n\t\t</main>\n\t\t<?php include_once 'components/footer.php'; ?>\n\t\t<?php include_once 'services/common-scripts.php'; ?>\n\t</body>\n</html>\n`);
catalog.push({path:canonical,file:page.slug+'.php',title,sections:includes});console.log('Built '+page.slug);
}
let queue=[...downloads];let cursor=0,fail=[];await Promise.all(Array.from({length:6},async()=>{while(cursor<queue.length){const [url,name]=queue[cursor++];if(fs.existsSync(path.join(root,name)))continue;try{write(name,await get(url))}catch(e){fail.push(e.message)}}}));write('docs/assets.json',JSON.stringify(manifest,null,2));write('docs/routes.json',JSON.stringify(catalog,null,2));write('docs/download-errors.json',JSON.stringify(fail,null,2));console.log({pages:catalog.length,assets:queue.length,fail});
})().catch(e=>{console.error(e);process.exit(1)});
