<?php
return [
    '/index.php'=>'/', '/index.html'=>'/', '/about'=>'/sobre-eurodronex',
    '/login'=>'/acceso', '/pagina-de-privacidad'=>'/politica-de-privacidad',
    '/pagina-de-privacidad/'=>'/politica-de-privacidad',
    '/sitemap_index.xml'=>'/sitemap.xml', '/wp-sitemap.xml'=>'/sitemap.xml',
    '/about/'=>'/sobre-eurodronex',
    '/inspeccion-tecnica-con-drones'=>'/servicios/inspeccion-tecnica-con-drones',
    '/inspeccion-tecnica-con-drones/'=>'/servicios/inspeccion-tecnica-con-drones',
    '/termografia-con-dron'=>'/servicios/termografia-con-dron',
    '/termografia-con-dron/'=>'/servicios/termografia-con-dron',
    '/fotogrametria-3d-edificios'=>'/servicios/fotogrametria-3d-edificios',
    '/fotogrametria-3d-edificios/'=>'/servicios/fotogrametria-3d-edificios',
    '/diagnostico-fachadas'=>'/servicios/diagnostico-fachadas',
    '/diagnostico-fachadas/'=>'/servicios/diagnostico-fachadas',
    '/seguimiento-de-obra'=>'/servicios/seguimiento-de-obra',
    '/seguimiento-de-obra/'=>'/servicios/seguimiento-de-obra',
    '/streaming'=>'/servicios/streaming', '/streaming/'=>'/servicios/streaming',
    '/inspeccion-precompra'=>'/servicios/inspeccion-precompra',
    '/inspeccion-precompra/'=>'/servicios/inspeccion-precompra',
    '/como-inspeccionar-cubiertas-sin-riesgo-ni-andamios/'=>'/blog/inspeccionar-cubiertas-sin-riesgo',
    '/como-inspeccionar-cubiertas-sin-riesgo-ni-andamios'=>'/blog/inspeccionar-cubiertas-sin-riesgo',
    '/por-que-un-arquitecto-con-drones-no-es-lo-mismo-que-un-piloto/'=>'/blog/arquitecto-drones-vs-piloto',
    '/por-que-un-arquitecto-con-drones-no-es-lo-mismo-que-un-piloto'=>'/blog/arquitecto-drones-vs-piloto',
    '/como-inspeccionar-un-edificio-sin-andamios-en-2026/'=>'/blog/inspeccionar-edificio-sin-andamios-2026',
    '/como-inspeccionar-un-edificio-sin-andamios-en-2026'=>'/blog/inspeccionar-edificio-sin-andamios-2026',
    '/category/uncategorized/'=>'/blog', '/category/uncategorized'=>'/blog',
    '/page-sitemap.xml'=>'/sitemap.xml','/post-sitemap.xml'=>'/sitemap.xml','/category-sitemap.xml'=>'/sitemap.xml',
];
