<?php require __DIR__ . '/../components/home/hero.php'; ?>
<?php require __DIR__ . '/../components/home/problem-solution.php'; ?>
<?php require __DIR__ . '/../components/home/manifesto.php'; ?>
<?php require __DIR__ . '/../components/home/pathologies.php'; ?>
<?php require __DIR__ . '/../components/home/services-preview.php'; ?>
<?php require __DIR__ . '/../components/home/methodology.php'; ?>
<?php require __DIR__ . '/../components/home/audiences.php'; ?>
<?php require __DIR__ . '/../components/home/credentials.php'; ?>
<?php require __DIR__ . '/../components/home/home-faq.php'; ?>
<?php require __DIR__ . '/../components/home/home-contact.php'; ?>
